version: '2'
services:
  mysql:
    container_name: mysql
    restart: always
    image: elenagin/my_sql:firsttry
    environment:
      MYSQL_ROOT_PASSWORD: 'blindinglights'
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  php:
    container_name: php
    restart: always
    image: elenagin/php:firsttry
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html



